// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaysp9XJzncqk6AzwLVcAVkuQsC57Ew-Y',
    appId: '1:868704184638:android:bb8d3310de5aa3a44a646f',
    messagingSenderId: '868704184638',
    projectId: 'carpooling-11c56',
    databaseURL: 'https://carpooling-11c56-default-rtdb.firebaseio.com',
    storageBucket: 'carpooling-11c56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Tq0-I8G5YUkRGgi2Av5QmNFJp8yu6Lk',
    appId: '1:868704184638:ios:7fa0b79401e791d14a646f',
    messagingSenderId: '868704184638',
    projectId: 'carpooling-11c56',
    databaseURL: 'https://carpooling-11c56-default-rtdb.firebaseio.com',
    storageBucket: 'carpooling-11c56.appspot.com',
    iosClientId: '868704184638-2dcmkkl4am1kc2hvjgsffhktaqui531h.apps.googleusercontent.com',
    iosBundleId: 'com.example.carpoolingPassenger',
  );
}
